---
- name: "Crear directorio de despliegue si no existe"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/deploy"
    state: directory
    mode: "0755"

- name: "Configurar app_actual para activepieces"
  ansible.builtin.set_fact:
    app_actual:
      nombre: "activepieces"
      dominio: "{{ lookup('vars', 'ACTIVEPIECES__DOMAIN', default=lookup('vars', 'ACTIVEPIECES_DOMAIN', default=ACTIVEPIECES__TRAEFIK_DASHBOARD_URL | default('activepieces.localhost'))) }}"
      usuario_admin: "{{ lookup('vars', 'ACTIVEPIECES__ADMIN_EMAIL', default=ACTIVEPIECES__TRAEFIK_USER | default('admin')) }}"
      acme_email: "{{ ACTIVEPIECES__ACME_EMAIL | default('admin@localhost') }}"
      password_db: "{{ lookup('vars', 'POSTGRES_PGVECTOR__POSTGRES_PASSWORD', default=ACTIVEPIECES__DB_PASSWORD | default('securepass')) }}"
      chatwoot_db_host: "postgres_pgvector"
      chatwoot_redis_host: "redis"

- name: "Generar archivo .env para activepieces"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/activepieces.env.j2"
    dest: "{{ playbook_dir }}/deploy/activepieces.env"
  register: config_env
  ignore_errors: true

- name: "Generar docker-compose para activepieces"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/activepieces.yml.j2"
    dest: "{{ playbook_dir }}/deploy/activepieces_stack.yml"
  register: config_stack
  ignore_errors: true

- name: "Desplegar Stack activepieces"
  ansible.builtin.command:
    cmd: "docker stack deploy -c activepieces_stack.yml activepieces"
    chdir: "{{ playbook_dir }}/deploy"
  when: not config_stack.failed | default(false)
