- hosts: localhost
  gather_facts: no
  vars:
    my_empty_var: ""
    my_null_var: null
  tasks:
    - debug:
        msg: "https://{{ lookup('vars', 'my_empty_var', default='') | default('localhost', true) }}"
    - debug:
        msg: "https://{{ lookup('vars', 'my_null_var', default='') | default('localhost', true) }}"
    - debug:
        msg: "https://{{ lookup('vars', 'missing_var', default='') | default('localhost', true) }}"
