---
- name: "Crear directorio de despliegue si no existe"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/deploy"
    state: directory
    mode: "0755"

- name: "Configurar app_actual para loki"
  ansible.builtin.set_fact:
    app_actual:
      nombre: "loki"
      dominio: "{{ lookup('vars', 'LOKI__DOMAIN', default=lookup('vars', 'LOKI_DOMAIN', default=lookup('vars', 'LOKI__TRAEFIK_DASHBOARD_URL', default='loki.localhost'))) }}"
      usuario_admin: "{{ lookup('vars', 'LOKI__ADMIN_EMAIL', default=lookup('vars', 'LOKI__TRAEFIK_USER', default='admin')) }}"
      acme_email: "{{ lookup('vars', 'LOKI__ACME_EMAIL', default='admin@localhost') }}"
      password_db: "{{ lookup('vars', 'POSTGRES_PGVECTOR__POSTGRES_PASSWORD', default=lookup('vars', 'LOKI__DB_PASSWORD', default='securepass')) }}"
      chatwoot_db_host: "postgres_pgvector"
      chatwoot_redis_host: "redis"

- name: "Generar archivo .env para loki"
  ansible.builtin.template:
    src: "loki.env.j2"
    dest: "{{ playbook_dir }}/deploy/loki.env"
  register: config_env
  ignore_errors: true

- name: "Generar docker-compose para loki"
  ansible.builtin.template:
    src: "loki.yml.j2"
    dest: "{{ playbook_dir }}/deploy/loki_stack.yml"
  register: config_stack
  ignore_errors: true

- name: "Desplegar Stack loki"
  ansible.builtin.command:
    cmd: "docker stack deploy -c loki_stack.yml loki"
    chdir: "{{ playbook_dir }}/deploy"
  when: not config_stack.failed | default(false)
