---
- name: "Crear directorio de despliegue si no existe"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/deploy"
    state: directory
    mode: "0755"

- name: "Configurar app_actual para dify"
  ansible.builtin.set_fact:
    app_actual:
      nombre: "dify"
      dominio: "{{ lookup('vars', 'DIFY__DOMAIN', default=lookup('vars', 'DIFY_DOMAIN', default=DIFY__TRAEFIK_DASHBOARD_URL | default('dify.localhost', true))) }}"
      usuario_admin: "{{ lookup('vars', 'DIFY__ADMIN_EMAIL', default=DIFY__TRAEFIK_USER | default('admin', true)) }}"
      acme_email: "{{ DIFY__ACME_EMAIL | default('admin@localhost', true) }}"
      password_db: "{{ lookup('vars', 'POSTGRES_PGVECTOR__POSTGRES_PASSWORD', default=DIFY__DB_PASSWORD | default('securepass', true)) }}"
      chatwoot_db_host: "postgres_pgvector"
      chatwoot_redis_host: "redis"

- name: "Generar archivo .env para dify"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/dify.env.j2"
    dest: "{{ playbook_dir }}/deploy/dify.env"
  register: config_env
  ignore_errors: true

- name: "Generar docker-compose para dify"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/dify.yml.j2"
    dest: "{{ playbook_dir }}/deploy/dify_stack.yml"
  register: config_stack
  ignore_errors: true

- name: "Desplegar Stack dify"
  ansible.builtin.command:
    cmd: "docker stack deploy -c {{ playbook_dir }}/deploy/dify_stack.yml dify"
  when: not config_stack.failed | default(false)
