---
- name: "Crear directorio de despliegue si no existe"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/deploy"
    state: directory
    mode: "0755"

- name: "Configurar app_actual para typebot"
  ansible.builtin.set_fact:
    app_actual:
      nombre: "typebot"
      dominio: "{{ lookup('vars', 'TYPEBOT__DOMAIN', default=lookup('vars', 'TYPEBOT_DOMAIN', default=TYPEBOT__TRAEFIK_DASHBOARD_URL | default('typebot.localhost'))) }}"
      usuario_admin: "{{ lookup('vars', 'TYPEBOT__ADMIN_EMAIL', default=TYPEBOT__TRAEFIK_USER | default('admin')) }}"
      acme_email: "{{ TYPEBOT__ACME_EMAIL | default('admin@localhost') }}"
      password_db: "{{ lookup('vars', 'POSTGRES_PGVECTOR__POSTGRES_PASSWORD', default=TYPEBOT__DB_PASSWORD | default('securepass')) }}"
      chatwoot_db_host: "postgres_pgvector"
      chatwoot_redis_host: "redis"

- name: "Generar archivo .env para typebot"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/typebot.env.j2"
    dest: "{{ playbook_dir }}/deploy/typebot.env"
  register: config_env
  ignore_errors: true

- name: "Generar docker-compose para typebot"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/typebot.yml.j2"
    dest: "{{ playbook_dir }}/deploy/typebot_stack.yml"
  register: config_stack
  ignore_errors: true

- name: "Desplegar Stack typebot"
  ansible.builtin.command:
    cmd: "docker stack deploy -c typebot_stack.yml typebot"
    chdir: "{{ playbook_dir }}/deploy"
  when: not config_stack.failed | default(false)
