---
- name: "Crear directorio de despliegue si no existe"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/deploy"
    state: directory
    mode: "0755"

- name: "Configurar app_actual para portainer"
  ansible.builtin.set_fact:
    app_actual:
      nombre: "portainer"
      dominio: "{{ PORTAINER__DOMAIN | default('portainer.localhost', true) }}"
      acme_email: "{{ TRAEFIK__ACME_EMAIL | default('admin@localhost', true) }}"

- name: "Generar archivo .env para portainer"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/portainer.env.j2"
    dest: "{{ playbook_dir }}/deploy/portainer.env"
  register: config_env

- name: "Generar docker-compose para portainer"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/portainer.yml.j2"
    dest: "{{ playbook_dir }}/deploy/portainer_stack.yml"
  register: config_stack

- name: "🚀 Desplegar Stack portainer en Docker Swarm"
  ansible.builtin.command:
    cmd: "docker stack deploy -c {{ playbook_dir }}/deploy/portainer_stack.yml portainer"
  when: not config_stack.failed | default(false)
  register: stack_deploy
  changed_when: "'Creating' in stack_deploy.stdout or 'Updating' in stack_deploy.stdout"
