---
- name: "Crear directorio de secrets si no existe"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/secrets"
    state: directory
    mode: "0700"

- name: "Crear directorio de despliegue si no existe"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/deploy"
    state: directory
    mode: "0755"

- name: "Configurar app_actual para glpi"
  ansible.builtin.set_fact:
    app_actual:
      nombre: "glpi"
      dominio: "{{ lookup('vars', 'GLPI__DOMAIN', default='glpi.localhost') }}"
      password_db: "{{ lookup('vars', 'MARIADB__MYSQL_ROOT_PASSWORD', default=MARIADB__MYSQL_ROOT_PASSWORD | default('securepass', true)) }}"

- name: "Generar archivo .env para glpi en secrets/"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/glpi.env.j2"
    dest: "{{ playbook_dir }}/secrets/glpi.env"
  register: config_env
  ignore_errors: true

- name: "Generar docker-compose para glpi"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/glpi.yml.j2"
    dest: "{{ playbook_dir }}/deploy/glpi_stack.yml"
  register: config_stack
  ignore_errors: true

- name: "Desplegar Stack glpi"
  ansible.builtin.command:
    cmd: "docker stack deploy -c {{ playbook_dir }}/deploy/glpi_stack.yml glpi"
  when: not config_stack.failed | default(false)
