---
- name: "Crear directorio de despliegue si no existe"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/deploy"
    state: directory
    mode: "0755"

- name: "Configurar app_actual para prometheus"
  ansible.builtin.set_fact:
    app_actual:
      nombre: "prometheus"
      dominio: "{{ lookup('vars', 'PROMETHEUS__DOMAIN', default=lookup('vars', 'PROMETHEUS_DOMAIN', default='prometheus.localhost')) }}"
      usuario_admin: "{{ lookup('vars', 'PROMETHEUS__USER', default=lookup('vars', 'PROMETHEUS_USER', default='admin')) }}"
      acme_email: "{{ lookup('vars', 'PROMETHEUS__ACME_EMAIL', default='admin@localhost') }}"
      password_db: "{{ lookup('vars', 'PROMETHEUS__PASSWORD', default='securepass') }}"

- name: "Generar archivo .env para prometheus"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/prometheus.env.j2"
    dest: "{{ playbook_dir }}/deploy/prometheus.env"
  register: config_env

- name: "Generar docker-compose para prometheus"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/prometheus.yml.j2"
    dest: "{{ playbook_dir }}/deploy/prometheus_stack.yml"
  register: config_stack

- name: "Desplegar Stack prometheus"
  ansible.builtin.command:
    cmd: "docker stack deploy -c {{ playbook_dir }}/deploy/prometheus_stack.yml prometheus"
  when: not config_stack.failed | default(false)
