---
- name: "Crear directorio de despliegue si no existe"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/deploy"
    state: directory
    mode: "0755"

- name: "Configurar app_actual para evolution_api"
  ansible.builtin.set_fact:
    app_actual:
      nombre: "evolution_api"
      dominio: "{{ lookup('vars', 'EVOLUTION_API__EVOLUTION_API_DOMAIN', default=lookup('vars', 'EVOLUTION_API_DOMAIN', default='evolution.localhost')) }}"
      acme_email: "{{ vars.get('TRAEFIK__ACME_EMAIL', 'admin@localhost') }}"
      api_key: "{{ vars.get('EVOLUTION_API__EV_API_KEY', 'securekey') }}"
      mongo_pass: "{{ vars.get('MONGODB__MONGODB_ROOT_PASSWORD', 'securepass') }}"

- name: "Generar archivo .env para evolution_api"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/evolution.env.j2"
    dest: "{{ playbook_dir }}/deploy/evolution_api.env"
  register: config_env

- name: "Generar docker-compose para evolution_api"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/evolution.yml.j2"
    dest: "{{ playbook_dir }}/deploy/evolution_api_stack.yml"
  register: config_stack

- name: "🚀 Desplegar Stack evolution_api en Docker Swarm"
  ansible.builtin.command:
    cmd: "docker stack deploy -c evolution_api_stack.yml evolution_api"
    chdir: "{{ playbook_dir }}/deploy"
  when: not config_stack.failed | default(false)
  register: stack_deploy
  changed_when: "'Creating' in stack_deploy.stdout or 'Updating' in stack_deploy.stdout"
