---
- name: "Crear directorio de secrets si no existe"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/secrets"
    state: directory
    mode: "0700"

- name: "Crear directorio de despliegue si no existe"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/deploy"
    state: directory
    mode: "0755"

- name: "Configurar app_actual para evolution_api"
  ansible.builtin.set_fact:
    app_actual:
      nombre: "evolution_api"
      dominio: "{{ lookup('vars', 'EVOLUTION_API__DOMAIN', default=lookup('vars', 'EVOLUTION_API_DOMAIN', default='evolution.localhost')) }}"
      acme_email: "{{ lookup('vars', 'TRAEFIK__ACME_EMAIL', default='admin@localhost') }}"
      api_key: "{{ lookup('vars', 'EVOLUTION_API__EV_API_KEY', default='securekey') }}"
      password_db: "{{ lookup('vars', 'POSTGRES_PGVECTOR__POSTGRES_PASSWORD', default='securepass') }}"
      maria_user: "{{ lookup('vars', 'MARIADB__MARIADB_ROOT_USERNAME', default='admin') }}"
      maria_pass: "{{ lookup('vars', 'MARIADB__MYSQL_ROOT_PASSWORD', default=MARIADB__MYSQL_ROOT_PASSWORD | default('securepass', true)) }}"

- name: "Generar archivo .env para evolution_api en secrets/"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/evolution.env.j2"
    dest: "{{ playbook_dir }}/secrets/evolution_api.env"
  register: config_env

- name: "Generar docker-compose para evolution_api"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/evolution.yml.j2"
    dest: "{{ playbook_dir }}/deploy/evolution_api_stack.yml"
  register: config_stack

- name: "🚀 Desplegar Stack evolution_api en Docker Swarm"
  ansible.builtin.command:
    cmd: "docker stack deploy -c {{ playbook_dir }}/deploy/evolution_api_stack.yml evolution_api"
  when: not config_stack.failed | default(false)
  register: stack_deploy
  changed_when: "'Creating' in stack_deploy.stdout or 'Updating' in stack_deploy.stdout"
