---
- name: "Crear directorio de secrets si no existe"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/secrets"
    state: directory
    mode: "0700"

- name: "Crear directorio de despliegue si no existe"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/deploy"
    state: directory
    mode: "0755"

- name: "Configurar app_actual para docuseal"
  ansible.builtin.set_fact:
    app_actual:
      nombre: "docuseal"
      dominio: "{{ lookup('vars', 'DOCUSEAL__DOMAIN', default='docuseal.localhost') }}"

- name: "Generar archivo .env para docuseal en secrets/"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/docuseal.env.j2"
    dest: "{{ playbook_dir }}/secrets/docuseal.env"
  register: config_env
  ignore_errors: true

- name: "Generar docker-compose para docuseal"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/docuseal.yml.j2"
    dest: "{{ playbook_dir }}/deploy/docuseal_stack.yml"
  register: config_stack
  ignore_errors: true

- name: "Desplegar Stack docuseal"
  ansible.builtin.command:
    cmd: "docker stack deploy -c {{ playbook_dir }}/deploy/docuseal_stack.yml docuseal"
  when: not config_stack.failed | default(false)
