---
- name: "Crear directorio de despliegue si no existe"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/deploy"
    state: directory
    mode: "0755"

- name: "Configurar app_actual para chatwoot"
  ansible.builtin.set_fact:
    app_actual:
      nombre: "chatwoot"
      dominio: "{{ lookup('vars', 'CHATWOOT__CHATWOOT_DOMAIN', default=CHATWOOT_DOMAIN | default('chatwoot.localhost', true)) }}"
      acme_email: "{{ vars.get('CHATWOOT__ACME_EMAIL', vars.get('TRAEFIK__ACME_EMAIL', 'admin@localhost')) }}"
      password_db: "{{ vars.get('POSTGRES_PGVECTOR__POSTGRES_PASSWORD', 'securepass') }}"
      secret_key_base: "{{ vars.get('CHATWOOT__SECRET_KEY_BASE', 'securekey') }}"
      redis_pass: "{{ vars.get('REDIS__PASSWORD', 'securepass') }}"

- name: "Generar archivo .env para chatwoot"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/chatwoot.env.j2"
    dest: "{{ playbook_dir }}/deploy/chatwoot.env"
  register: config_env

- name: "Generar docker-compose para chatwoot"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/chatwoot.yml.j2"
    dest: "{{ playbook_dir }}/deploy/chatwoot_stack.yml"
  register: config_stack

- name: "🚀 Desplegar Stack chatwoot en Docker Swarm"
  ansible.builtin.command:
    cmd: "docker stack deploy -c {{ playbook_dir }}/deploy/chatwoot_stack.yml chatwoot"
  when: not config_stack.failed | default(false)
  register: stack_deploy
  changed_when: "'Creating' in stack_deploy.stdout or 'Updating' in stack_deploy.stdout"
